export const ADD_TO_CART_REQUEST = 'ADD_TO_CART_REQUEST'
export const ADD_TO_CART_SUCCESS = 'ADD_TO_CART_SUCCESS'
export const ADD_TO_CART_ERROR = 'ADD_TO_CART_ERROR'

export const FETCH_CART_REQUEST = 'FETCH_CART_REQUEST'
export const FETCH_CART_SUCCESS = 'FETCH_CART_SUCCESS'
export const FETCH_CART_ERROR = 'FETCH_CART_ERROR'

export const REMOVE_CART_REQUEST = 'REMOVE_CART_REQUEST'
export const REMOVE_CART_SUCCESS = 'REMOVE_CART_SUCCESS'
export const REMOVE_CART_ERROR = 'REMOVE_CART_ERROR'

export const CHECKOUT_CART_REQUEST = 'CHECKOUT_CART_REQUEST'
export const CHECKOUT_CART_SUCCESS = 'CHECKOUT_CART_SUCCESS'
export const CHECKOUT_CART_ERROR = 'CHECKOUT_CART_ERROR'

export const REMOVE_ONE_FROM_CART_REQUEST = 'REMOVE_ONE_FROM_CART_REQUEST'
export const REMOVE_ONE_FROM_CART_SUCCESS = 'REMOVE_ONE_FROM_CART_SUCCESS'
export const REMOVE_ONE_FROM_CART_ERROR = 'REMOVE_ONE_FROM_CART_ERROR'

export const ADD_CAKE_ORDER_REQUEST = 'ADD_CAKE_ORDER_REQUEST'
export const ADD_CAKE_ORDER_SUCCESS = 'ADD_CAKE_ORDER_SUCCESS'
export const ADD_CAKE_ORDER_ERROR = 'ADD_CAKE_ORDER_ERROR'



export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'
export const FETCH_CART = 'FETCH_CART'
export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_ONE_FROM_CART = 'REMOVE_ONE_FROM_CART'
export const ADD_CAKE_ORDER = 'ADD_CAKE_ORDER'


