export const LIST_ORDER_REQUEST = 'LIST_ORDER_REQUEST'
export const LIST_ORDER_SUCCESS = 'LIST_ORDER_SUCCESS'
export const LIST_ORDER_ERROR = 'LIST_ORDER_ERROR'

export const LIST_ORDER = 'LIST_ORDER'